typography_spectrum: 0.41153
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.25845893169753253
  lightness: 0.9916288282256573
  saturation: 0.03242517448961735
  rhythmicContrast: 0.8942477868404239
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.52421
analytics:
  google: null
  facebook: null
  twitter: null
name: kitchensync
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: kitchen.sync
description: on ongoing investigation of food + cooking
purpose: []
